import { Component, OnInit,  } from '@angular/core';
import { Router } from '@angular/router';
import { HandleDataService } from 'src/app/common/services/Data/handle-data.service';
import { handleFunction } from 'src/app/common/services/functions/handleFunctions';
import { SecurityCheckService } from 'src/app/common/services/Data/security-check.service';
import { ApiCallsService } from '../../../common/services/ApiCalls/ApiCalls.service';
import * as jsPDF from 'jspdf';
import 'jspdf-autotable';

@Component({
  selector: 'app-truck-loading',
  templateUrl: './truck-loading.component.html',
  styleUrls: ['./truck-loading.component.css'],
  providers: [ApiCallsService]
})
export class TruckLoadingComponent implements OnInit {
  public today;
  public date ;
  public alltrucks=[];
  public alltrucks2=[];
  public fy = '2026'
  public timeLog='04'
  public alltrucks3={};
  public tempType='';
  public mainData=false;
  public bigJJ;
  public bigII;
  public advbalarray=[];
  public ownerdetailslist;
  public selectedDate;
  public selectedTruck;
  constructor(public apiCallservice: ApiCallsService,public handleF:handleFunction,public handledata:HandleDataService,public router:Router,public sec:SecurityCheckService) {if(!this.sec.login){
    this.router.navigate([''])
  }
  }

  ngOnInit() {
    this.fetchBasic()
  }

  fetchBasic() {
    this.ownerdetailslist = [];
    this.ownerdetailslist = this.sec.arr;
  }
  fetchMain(){
    let tempObj = {};
    tempObj['tablename'] = ''
    tempObj['method'] = 'getTruckDetailsbyoid';
    tempObj['id']=this.sec.userid;
    tempObj['fy']=this.fy;
    tempObj['month']=this.timeLog;

    this.apiCallservice.handleData_New_python('commoninformation', 1, tempObj, true)
      .subscribe((res: any) => {
        this.alltrucks=[];
          this.alltrucks = res.Data;
          this.mainData=res.Data.length>0?true:false;
      });
  }

    savePayment(i,j,type){
    this.bigII=i;
    this.bigJJ=j;
    this.advbalarray = this.alltrucks[this.bigJJ][type]
      
    this.tempType=type;
  }

      bankRec(i) {
      
let data=i;
    var doc = new jsPDF()
    doc.setFontSize('10');
    doc.setTextColor(0,0,0);

    var img = new Image();
    img.src = '../../../assets/images/cnrb.png';

    var img2 = new Image();
    img2.src = '../../../assets/images/N.png';

    doc.addImage(img, 'PNG', 20, 6, 110, 20);//add if else
    doc.addImage(img2, 'PNG', 160, 1, 40, 30);//add if else

    doc.text('Receipt generated by NITIN ROADWAYS AND CARGO MOVERS',50, 150)

    doc.setDrawColor(163,0,0);
    doc.setLineWidth(0.5);
    doc.line(15, 29, 195, 29);

    doc.setFontSize('18');
    doc.setFontType('bold');
    doc.setTextColor(30, 150, 190);

    doc.text('Internal Transaction Acknowledgement',45,50)
    doc.setTextColor(80, 168, 72);

    doc.setFontSize('16');
    doc.text('Money Transferred Succesfully',60,60)

    doc.setFontSize('12');
    doc.setTextColor(30, 150, 190);

    doc.text('From Nitin Roadways',25,90);
    doc.setTextColor(0,0,0);
    doc.text('To : ',25,100);
    doc.text('Date : ',25,110);
    doc.text('Amount : ',25,120);
    doc.text('Reference : ',25,130)

    doc.setTextColor(30, 150, 190);
    doc.text(this.alltrucks[this.bigJJ].truckName.truckno,60,100);
    doc.text(this.handleF.getDateddmmyy(data.date),60,110);
    doc.text(String(data.amount),60,120);
    doc.text(data.reference,60,130)
    

    doc.save(this.alltrucks[this.bigJJ].truckName.truckno+'_'+data.amount+'.pdf')
  }


}
