version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Building"
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod --aot
      - echo "Build successful"
# artifacts:
#   files:
#     - 'NRCM/**'
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: NRCM